#cloud-config

packages: ['docker']

write_files:
  - path: /genesis.json
    permissions: '0644'
    encoding: base64
    content: ${base64encode(genesis_json)}

  - path: /docker-compose.yaml
    permissions: '0644'
    encoding: base64
    content: ${base64encode(docker_compose)}

runcmd:
  - mkdir /chain
  - mount -t efs ${efs_id}:/explorer/geth /chain
  - mount -t efs ${efs_id}:/explorer/mongo /mongo

  - chmod 777 /chain
  - chmod 777 /mongo

  - systemctl start docker.service
  - pip3 install docker-compose

  - python3 /get_secret.py --name "circles-ws-secret" --value "ws-secret" --output /secrets/ws-secret

  - bash -c 'BOOTNODE_ADDRESS=${bootnode_address} ETHSTATS_ADDRESS=${ethstats_address} WS_SECRET="$(cat /secrets/ws-secret)" WEB_PORT="${explorer_port}" docker-compose -f /docker-compose.yaml up'
