version: "2"
services:
  REST:
    image: blkio10/explorer-free:1.0.0
    container_name: blk-explorer-free
    ports:
        - 8081:8081
    environment:
        - JAVA_OPTS=
        - EXPLORER_PORT=8081
        - NODE_ENDPOINT=geth:8545
        - MONGO_CLIENT_URI=mongodb://localhost:28017
        - MONGO_DB_NAME=circles
        - UI_IP=http://localhost:5000
    depends_on:
        - mongodb
    network_mode: "host"

  web:
    image: blkio10/explorer-ui-free:1.0.0
    container_name: blk-explorer-ui-free
    ports:
        - ${WEB_PORT}:5000
    environment:
        - REACT_APP_EXPLORER=http://localhost:8081

  mongodb:
    image: mongo:3.4.10
    container_name: blk-mongodb-free
    ports:
        - 28017:27017
    entrypoint: mongod --smallfiles --logpath=/dev/null --bind_ip "0.0.0.0"

  init-geth:
    image: ethereum/client-go:latest
    container_name: init-geth
    volumes:
      - /genesis.json:/genesis.json
      - /chain:/chain
    command: --datadir /chain init /genesis.json

  geth:
    image: ethereum/client-go:latest
    container_name: geth
    volumes:
      - /chain:/chain
    command: --datadir /chain --rpc --rpcapi="eb3,eth,net,debug" --rpcport "8545" --rpcaddr "0.0.0.0" --syncmode "full" --gcmode=archive --networkid "46781" --bootnodes "enode://07d24a7a560c4b4011b71c94db03f48afba2bbb0d37b7a403d25bd86bb4d55e521b9f646371b99fdca194423a412d526613c991c493ca84af93e9c01e184f56a@${BOOTNODE_ADDRESS}" --ethstats "explorer:${WS_SECRET}@${ETHSTATS_ADDRESS}"
    depends_on:
      - init-geth
