#cloud-config

# -----------------------------------------------------------------------
# - Mounts EFS volume
# - Installs docker + docker-compose
# - Brings up all services specified in the docker-compose.yaml
# -----------------------------------------------------------------------

package_update: true

groups:
  - docker

packages: ['docker', 'amazon-efs-utils']

write_files:
  - path: /home/ec2-user/docker-compose.yaml
    permissions: '0644'
    encoding: base64
    content: ${base64encode(docker_compose_file)}

runcmd:
  # mount efs filesystem
  - sudo mkdir -p /data
  - sudo mount -t efs ${efs_id}:/ /data

  # prepare docker
  - service docker restart
  - usermod -a -G docker ec2-user

  # install docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${docker_compose_version}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # start services
  - /usr/local/bin/docker-compose -f /home/ec2-user/docker-compose.yaml up
