version: '3'
services:
  ethstats:
    image: puppeth/ethstats
    ports:
      - "3000:3000"
    restart: always
    environment:
      WS_SECRET: circles-ethstats
    networks:
      circles:

  bootnode:
    image: ethereum/client-go:alltools-stable
    restart: always
    ports:
      - "30301:30301"
    command: bootnode -nodekeyhex 258b9f9b54ac3d165b96897ed154bbbc1bd4d2ca054479ea7f9fe7266171d97c
    networks:
      circles:
        ipv4_address: 10.0.0.50

  sealer:
    image: ethereum/client-go
    restart: always
    command: --networkid 46781 --rpc --rpccorsdomain "*" --rpcaddr "10.0.0.51" --rpcapi "db,eth,net,web3,personal,admin,miner" --mine --datadir /data/sealer --keystore /keystore --unlock d0602f13c58c3dd37f6ef1d4997c1af506adb904 --password /keystore/password --ethstats "sealer:circles-ethstats@ethstats:3000" --bootnodes "enode://0c017f5db205d9b41573d060c8578cd95b70f45d5dcb4db471e05e8cdbf69d867af5f3ff4ec805dff2109e9ae6ee8266a4a8d95227b1223b32620b0dde8430f9@10.5.0.5:30301"
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data/sealer:/data/sealer
      - ./data/genesis.json:/data/genesis.json:ro
      - ./keystore:/keystore
    networks:
      circles:
        ipv4_address: 10.0.0.51

networks:
  circles:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
