version: '3'
services:
  ethstats:
    image: puppeth/ethstats
    ports:
      - "3000:3000"
    restart: always
    environment:
      WS_SECRET: "${WS_SECRET}"

  sealer:
    image: ethereum/client-go
    restart: always
    command: --networkid 46781 --rpc --rpccorsdomain "*" --rpcaddr "0.0.0.0" --rpcapi "db,eth,net,web3,personal,admin,miner" --mine --datadir /data/sealer --keystore /keystore --unlock e477eaddcb3d365061083f60f14a4cf4d2782f96 --password /keystore/password --ethstats "sealer:${WS_SECRET}@ethstats:3000"
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data/sealer:/data/sealer:Z
      - ./secrets/sealer-account:/keystore/sealer-account:ro
      - ./secrets/sealer-account-password:/keystore/password:ro
