version: '3'
services:
  ethstats:
    image: puppeth/ethstats
    ports:
      - "3000:3000"
    restart: always
    environment:
      WS_SECRET: "${WS_SECRET}"
    networks:
      circles:

  bootnode:
    image: ethereum/client-go:alltools-stable
    restart: always
    ports:
      - "30301:30301"
    command: bootnode -nodekey /bootnode-key
    volumes:
      - ./secrets/bootnode-key:/bootnode-key:ro
    networks:
      circles:
        ipv4_address: 10.0.0.50

  sealer:
    image: ethereum/client-go
    restart: always
    command: --networkid 46781 --rpc --rpccorsdomain "*" --rpcaddr "10.0.0.51" --rpcapi "db,eth,net,web3,personal,admin,miner" --mine --datadir /data/sealer --keystore /keystore --unlock e477eaddcb3d365061083f60f14a4cf4d2782f96 --password /keystore/password --ethstats "sealer:${WS_SECRET}@ethstats:3000" --bootnodes "enode://976626fcad5feb994ab05ed984ad7d91bbea7d86e02a1ac04b7b0ef5fe3f1c09fc57cde95c0a6201c208469bccce228997946ebeedb828ddafcf03d20f982c8f@10.5.0.5:30301"
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./data/sealer:/data/sealer:Z
      - ./secrets/sealer-account:/keystore/sealer-account:ro
      - ./secrets/sealer-account-password:/keystore/password:ro
    networks:
      circles:
        ipv4_address: 10.0.0.51

networks:
  circles:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
