  influxsrv:
    image: tutum/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    environment:
      - PRE_CREATE_DB=cadvisor

  cadvisor:
    image: google/cadvisor
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    ports:
      - "9090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    links:
      - influxsrv:influxsrv

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxsrv:influxsrv
    environment:
      - INFLUXDB_HOST=localhost
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root

  ethstats:
    image: puppeth/ethstats
    ports:
      - "3030:3030"
    restart: always
    environment:
      WS_SECRET: circles-ethstats

  bootnode:
    image: ethereum/client-go:alltools-stable
    restart: always
    ports:
      - "30301:30301"
    command: bootnode -nodekeyhex 258b9f9b54ac3d165b96897ed154bbbc1bd4d2ca054479ea7f9fe7266171d97c
    links:
      - ethstats

  miner:
    image: ethereum/client-go
    restart: always
    command: --ethstats "miner:circles-ethstats@ethstats:3000"
    ports:
      - "8545:8545"
      - "30303:30303"
    links:
      - ethstats
      - bootnode
