#cloud-config

package_update: true

packages: ['amazon-efs-utils']

write_files:
  - path: /genesis.json
    permissions: '0644'
    encoding: base64
    content: ${base64encode(genesis_json)}

runcmd:
  # mount efs filesystem
  - mkdir /chain
  - mount -t efs ${efs_id}:/rpc /chain

  # install geth
  - python3 /install_geth.py --version=${geth_version} --commit=${geth_commit} --md5=${geth_md5}

  # prepare genesis block
  - mkdir -p /chain
  - chmod 777 /chain
  - geth --datadir /chain init /genesis.json

  # get secrets
  - python3 /get_secret.py --name "circles-ws-secret" --value "ws-secret" --output /secrets/ws-secret

  # start rpc node
  - 'geth --networkid "${network_id}" --rpc --rpcapi="eb3,eth,net,debug" --rpcport "${rpc_port}" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --datadir "/chain" --keystore "/keystore" --ethstats "rpc:$(cat /secrets/ws-secret)@${ethstats_ip}:3000" --bootnodes "enode://${bootnode_enode}@${bootnode_ip}:${bootnode_port}"'
