#cloud-config

packages: ['awslogs', 'python36']

write_files:
  - path: /attach_resources.py
    permissions: '0644'
    encoding: base64
    content: ${base64encode(attach_resources_py)}

  - path: /etc/awslogs/awslogs.conf
    permissions: '0644'
    encoding: base64
    content: ${base64encode(awslogs_conf)}

runcmd:
  # configure & start logs
  - bash -c 'sed -i -e "s/<<!instance_id!>>/$(curl -s http://169.254.169.254/latest/meta-data/instance-id)/g" /etc/awslogs/awslogs.conf'
  - bash -c 'sed -i -e "s/us-east-1/eu-central-1/g" /etc/awslogs/awscli.conf'
  - service awslogs start

  # attach resources
  - python3 -m pip install pyasn1 boto3 retry
  - python3 /attach_resources.py --instance_id="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)" --interface_id=${eni_id} --volume_id=${volume_id} --service_name=${service_name}

  # format EBS if required
  - blkid -L data; FILESYSTEM_EXISTS=$?; if [[ $FILESYSTEM_EXISTS -ne 0 ]]; then echo "FORMATTING EBS VOLUME" && mkfs -t ext4 -L data /dev/xvdb; fi

  # mount EBS
  - mkdir -p /data
  - mount /dev/xvdb /data
  - chmod 777 /data

  # check data persistance
  - echo "$(date +%Y:%m:%d-%H:%M:%S) -- $(curl -s http://169.254.169.254/latest/meta-data/instance-id)" >> /data/mounted_in.txt
  - echo "EBS volume mount history:"
  - tail -50 /data/mounted_in.txt

  # join ecs cluster
  - echo ECS_CLUSTER=${ecs_cluster_name} >> /etc/ecs/ecs.config
