#cloud-config

packages: ['awslogs', 'python36']

write_files:
  - path: /write_extra_files.py
    permissions: '0644'
    encoding: base64
    content: ${base64encode(write_extra_files_py)}

  - path: /service/docker-compose.yaml
    permissions: '0644'
    encoding: base64
    content: ${base64encode(docker_compose_yaml)}

  - path: /etc/awslogs/awslogs.conf
    permissions: '0644'
    encoding: base64
    content: ${base64encode(awslogs_conf)}

runcmd:
  # configure & start logs
  - bash -c 'sed -i -e "s/<<!instance_id!>>/$(curl http://169.254.169.254/latest/meta-data/instance-id)/g" /etc/awslogs/awslogs.conf'
  - bash -c 'sed -i -e "s/us-east-1/eu-central-1/g" /etc/awslogs/awscli.conf'
  - service awslogs start


  # attach ENI
  - aws ec2 attach-network-interface --network-interface-id ${eni_id} --instance-id $(curl http://169.254.169.254/latest/meta-data/instance-id) --region eu-central-1 --device-index 1

  # attach EBS
  - aws ec2 attach-volume --volume-id ${volume_id} --instance-id $(curl http://169.254.169.254/latest/meta-data/instance-id) --region eu-central-1 --device /dev/xvdb
  - sleep 15s
  - blkid -L data; FILESYSTEM_EXISTS=$?
  - if [[ $FILESYSTEM_EXISTS -ne 0 ]]; then mkfs -t ext4 -L data /dev/xvdb; fi

  # mount EBS
  - mkdir -p /data
  - mount /dev/xvdb /data
  - chmod 777 /data

  # check data persistance
  - echo "$(date +%Y:%m:%d-%H:%M:%S) -- $(curl http://169.254.169.254/latest/meta-data/instance-id)" >> /data/mounted_in.txt
  - echo "EBS volume mount history:"
  - tail -50 /data/mounted_in.txt

  # deploy service
  - python3 /write_extra_files.py ${base64encode(extra_files)}
  - python3 -m pip install docker-compose
  - sudo -u ec2-user bash -c 'cd /service && /usr/local/bin/docker-compose up -d --no-color'
