#cloud-config

package_update: true

packages: ['python3']

users:
  - default

write_files:
  - path: /get_secret.py
    permissions: '0644'
    encoding: base64
    content: ${base64encode(get_secret_py)}

  - path: /install_geth.py
    permissions: '0644'
    encoding: base64
    content: ${base64encode(install_geth_py)}

runcmd:
  - pip3 install boto3
