#cloud-config

package_update: true

packages: ['amazon-efs-utils']

write_files:
  - path: /genesis.json
    permissions: '0644'
    encoding: base64
    content: ${base64encode(genesis_json)}

runcmd:
  # mount efs filesystem
  - mkdir /chain
  - mount -t efs ${efs_id}:/sealer /chain

  # install geth
  - python3 /install_geth.py --version=${geth_version} --commit=${geth_commit} --md5=${geth_md5}

  # prepare genesis block
  - mkdir -p /chain
  - chmod 777 /chain
  - geth --datadir /chain init /genesis.json

  # get secrets
  - python3 /get_secret.py --name "circles-secrets" --value "sealer-account" --output /keystore/sealer-keyfile
  - python3 /get_secret.py --name "circles-secrets" --value "sealer-account-password" --output /secrets/sealer-password
  - python3 /get_secret.py --name "circles-secrets" --value "ws-secret" --output /secrets/ws-secret

  # start sealer
  - geth --networkid ${network_id} --mine --datadir /chain --keystore /keystore --unlock ${sealer_account} --password /secrets/sealer-password --ethstats "sealer:$(cat /secrets/ws-secret)@${ethstats_ip}:3000" --bootnodes enode://${bootnode_enode}@${bootnode_ip}:${bootnode_port}
