version: '3'
services:
  rpc:
    build: .
    volumes:
      - /data:/chain
      - ./genesis.json:/genesis.json:ro
    ports:
      - ${port}:${port}
      - ${port}:${port}/udp
    logging:
      driver: awslogs
      options:
        awslogs-region: "eu-central-1"
        awslogs-group: "${log_group}"
